[package]
name = "formdata"
version = "0.7.2"
description = "Parsing of multipart/form-data"
authors = [
        "Mike Dilger <mike@optcomp.nz>",
        "Skyler Lipthay <skyler.lipthay@gmail.com>",
        ]
readme = "README.md"
repository = "https://github.com/mikedilger/formdata"
documentation = "https://mikedilger.github.io/formdata"
license = "MIT"
keywords = ["multipart", "form-data", "hyper", "http", "mime"]

[dependencies]
hyper = "^0.6"
httparse = "^1.0"
mime = "^0.1"
libc = "^0.1"
tempdir = "^0.3"
textnonce = "^0.1"
log = "^0.3"
