[package]
name = "formdata"
version = "0.8.4"
description = "Parsing of multipart/form-data"
authors = [
        "Mike Dilger <mike@optcomp.nz>",
        "Skyler Lipthay <skyler.lipthay@gmail.com>",
        ]
readme = "README.md"
repository = "https://github.com/mikedilger/formdata"
documentation = "https://mikedilger.github.io/formdata"
license = "MIT"
keywords = ["multipart", "form-data", "hyper", "http", "mime"]
build = "build.rs"

[features]
default = [ "rust-stable", "ssl" ]
rust-stable = [ "serde_codegen", "syntex", "textnonce/rust-stable" ]
rust-nightly = [ "serde_macros", "textnonce/rust-nightly" ]
ssl = ["hyper/ssl"]
# Deprecated feature names
with-syntex = [ "rust-stable" ]

[build-dependencies]
serde_codegen = { version = "0.7", optional = true }
syntex = { version = "^0", optional = true }

[dev-dependencies]
serde_json = "0.7"

[dependencies]
hyper = {version = "0.9", default-features = false }
httparse = "1.1"
mime = { version = "0.2", features = [ "serde" ] }
tempdir = "0.3"
textnonce = { version = "0.3.4", default-features = false }
log = "0.3"
serde = "0.7"
serde_macros = { version = "0.7", optional = true }
encoding = "0.2"
clippy = { version = "0.0", optional = true }
